#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'py-arduino-pub','console_scripts','Sending_py_order'
__requires__ = 'py-arduino-pub'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('py-arduino-pub', 'console_scripts', 'Sending_py_order')()
    )
